### ISSUE TITLE
How to change the color?

### ISSUE THREAD

**Issue by Sinarahimi** [shetmobile/MeowDateTimePicker#1]
Hi
How can I change the color of it? Does this depends on activity style or not?

**Comment by Dot01110011** [comment]
READ DESCRIPTION OF LIBRARY FIRST!
Add these lines to res/values/colors.xml
```
<color name="mdtp_accent_color">#009688</color>
<color name="mdtp_accent_color_dark">#00796b</color>
```

**Comment by Sinarahimi** [comment]
thank you my mistake
